branches:
  only:
    - master
env: CODECLIMATE_REPO_TOKEN=020fdb8a8da6518502f36d94bb21c2ce52da61d3c778cba8d4b35e9328c64502 
services:
  - redis-server
language: ruby
rvm:
  - 2.1.2
  - 2.1.1
  - 2.1.0
